### ISSUE TITLE
How can I acess the authnotifer outside of an widget e.g in an StateNotifierProvider?

### ISSUE THREAD

**Issue by cybr-dev** [lohanidamodar/flappwrite_account_kit#10]
How can I acess the AuthNotifer outside of an widget e.g in an StateNotifierProvider?
Thank you for your help!

**Comment by lohanidamodar** [comment]
Well, if you want to do that, create your own instance of `AuthNotifier` and provide it via your own provider instead.
I'm using inherited widget to provide instance of `AuthNotifier` so instead you can create your own instance of `AuthNotifier` and provide it. It's just a ChangeNotifier so it works.
